#!/bin/bash

# Prints an optical divider. Select the width by setting env "width" to an integer value. Defaults to 120.
function divider {
  if [ -z "${width}" ]; then
    width=120
  fi

  count=${width}
  while [ $count -ge 2 ]; do
    echo -n "="
    ((count--))
  done
  echo "="
  unset count
}


# If exist, execute /extra/init . Must exit and not stay in front
if [ -e "/extra/init" ]; then
  if [ ! -x "/extra/init" ]; then
    chmod +x "/extra/init"
  fi
  echo "Starting execution of your user-defined script (/extra/init):"
  /extra/init
  divider
fi

# Set Apache admin-mail if set
if [ ! -z "${SERVER_ADMIN}" ]; then
    sed -i'' "s#admin@your-domain\.com#${SERVER_ADMIN}#g" /etc/httpd/conf/httpd.conf
fi

# Set PHP date.timezone
if [ ! -z "$(php -i | egrep '^date.timezone => no value => no value')" ]; then
  if [ -z "${PHP_TZ}" ]; then
    PHP_TZ="Europe/Berlin"
  fi
  echo -e "\ndate.timezone = ${PHP_TZ}" >> /etc/php/php.ini
fi

# Print some parsed configs
echo "PHP settings:"
/usr/sbin/php -i
divider
echo "Apache parsed run setting:"
/usr/sbin/apachectl -S
divider
echo "Apache loaded modules:"
/usr/sbin/apachectl -M
divider
divider

# Start Apache
/usr/sbin/apachectl -t && /usr/sbin/apachectl -D FOREGROUND -k start
