#!/bin/bash

# Prints an optical divider. Select the width by setting env "width" to an integer value. Defaults to 120.
function divider {
  if [ -z "${width}" ]; then
    width=120
  fi

  count=${width}
  while [ $count -ge 2 ]; do
    echo -n "="
    ((count--))
  done
  echo "="
  unset count
}


# If exist, execute /extra/init . Must exit and not stay in front
if [ -e "/extra/init" ]; then
  if [ ! -x "/extra/init" ]; then
    chmod +x "/extra/init"
  fi
  echo "Starting execution of your user-defined script (/extra/init):"
  /extra/init
  divider
fi

# Print some parsed configs
echo "PHP settings:"
/usr/sbin/php -i
divider
echo "Apache parsed run setting:"
/usr/sbin/apachectl -S
divider
echo "Apache loaded modules:"
/usr/sbin/apachectl -M
divider
divider

# Start Apache
if [ -z "${SERVER_ADMIN}" ]; then
    export SERVER_ADMIN="you@example.com"
fi
/usr/sbin/apachectl -t && /usr/sbin/apachectl -k start
