version: "3.4"

services:
  webapp:
    build:
      context: .
      args:
        MYSQL_ROOT_PASSWORD: set_to_something_better
        MYSQL_DATABASE: projectsend
    image: derjudge/projectsend
    restart: unless-stopped
    volumes:
      - ./data:/mnt/data
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      MYSQL_ROOT_PASSWORD: set_to_something_better
      MYSQL_DATABASE: projectsend
    entrypoint: /usr/local/bin/wait4db.sh
  
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: set_to_something_better
      MYSQL_DATABASE: projectsend

volumes:
  db-data:
